[project]
name = "udfs-ai"
version = "0.1.0"
description = "Fused MCP: Setting up MCP Servers for Data Scientists"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "anthropic>=0.49.0",
    "fused[all]>=1.15.0",
    "jupyterlab>=4.3.6",
    "mcp[cli]>=1.4.1",
]
